<a href="https://colab.research.google.com/github/jh941213/TextMining/blob/main/10_model_save_load.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

import numpy as np
import pandas as pd

import pickle
import joblib

In [ ]:
iris = load_iris()

x_data = iris.data
y_data = iris.target.reshape(-1, 1)

dataset = np.concatenate((x_data, y_data), axis=1)
col_names = iris.feature_names + ['label']

In [ ]:
df_iris = pd.DataFrame(dataset, columns=col_names)
df_iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, stratify=y_data)

In [ ]:
print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

(array([0, 1, 2]), array([37, 37, 38]))
(array([0, 1, 2]), array([13, 13, 12]))


In [ ]:
model = LogisticRegression()
model.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
model.score(x_test, y_test)

0.9210526315789473

In [ ]:
model.coef_, model.intercept_

(array([[-0.4893099 ,  0.76893354, -2.27394514, -0.97463046],
        [ 0.30939506, -0.50781827, -0.06977633, -0.95529302],
        [ 0.17991484, -0.26111527,  2.34372147,  1.92992348]]),
 array([  9.77816949,   3.32619429, -13.10436378]))

##### pickle dump, load 이용

In [ ]:
with open('logistic.pickle', 'wb') as f:
    pickle.dump(model, f)
    
with open('logistic.pickle', 'rb') as f:
    model_pkl = pickle.load(f)

In [ ]:
# pickle.dump(model, open("logistic.pickle", 'wb'))
# model_pkl = pickle.load(open("logistic.pickle", 'rb'))

In [ ]:
model_pkl.score(x_test, y_test)

0.9210526315789473

##### joblib 이용

In [ ]:
joblib.dump(model, 'joblib.pickle')

['joblib.pickle']

In [ ]:
model_jlb = joblib.load('joblib.pickle')
model_jlb.score(x_test, y_test)

0.9210526315789473